### PR TITLE
OneDrive for Business support

### PR DESCRIPTION
**Pull request by rootik**
Hello
Thank you for a great script. I have added OneDrive for business support as a separate script/configuration. OneDrive for Business API is significantly different from OneDrive Personal API.
Feel free to discuss this pull request.

rootik

### CODE REVIEW

**Comment by fkalis** [comment]
Hello and thank you for your contribution. I really appreciate this, but before I accept your pull request, I will take a closer look at the source code, especially at the newly introduced function `curl_discover_uri` and its usage.

**Comment by fkalis** [comment]
I am not able to test your implementation due to the lack of an Azure account.

Please make sure that both simple uploads and chunked uploads work (both implementations still exist, so I assume both ways should work with OneDrive for Business) for existing folders, the root folder, and a non-existing folder.

**Comment by rootik** [comment]
Hello.
I revised the code. You are right, `api_base_url` was a relict.
`api_resource_id` is used according to documentaion [https://dev.onedrive.com/auth/aad_oauth.htm](url)
I experimented with chunked upload and now it works as it should.
This is a part of debug output from my test:
```
2016-08-25 11:09:47 Uploading chunk 24 of 'largefile.dat'
2016-08-25 11:09:47 Content-Length: 7864320
2016-08-25 11:09:47 Content-Range: bytes 243793920-251658239/251658240
2016-08-25 11:09:51 Status code: 201
2016-08-25 11:09:51 Upload of chunk 24 of 'largefile.dat' finished (Code: 201)
Successfully uploaded 'largefile.dat' as 'largefile.dat'
```

**Comment by rootik** [comment]
BTW, simple file upload works for this large file too :)

**Comment by rootik** [comment]
Chunked uploading to non-existent folder test:
```
./onedriveb-upload -d -f test largefile.dat
2016-08-25 13:25:57 Searching for 'test' in ''
2016-08-25 13:25:58 Creating folder 'test' in ''
2016-08-25 13:26:00 api_folder_id is now '01KB37ZVT6RYOY5M6DDVEKCMBR6DX7C26Q'
2016-08-25 13:26:00 Size of largefile.dat is more than 104857600 bytes, will use chunked upload
2016-08-25 13:26:04 Requesting upload session for 'largefile.dat'
2016-08-25 13:26:04 Uploading 'largefile.dat' as 'largefile.dat' into 01KB37ZVT6RYOY5M6DDVEKCMBR6DX7C26Q
2016-08-25 13:26:07 Uploading chunk 0 of 'largefile.dat'
2016-08-25 13:26:07 Content-Length: 10158080
2016-08-25 13:26:07 Content-Range: bytes 0-10158079/251658240
2016-08-25 13:26:10 Status code: 202
2016-08-25 13:26:10 Upload of chunk 0 of 'largefile.dat' finished (Code: 202)
2016-08-25 13:26:12 Uploading chunk 1 of 'largefile.dat'
2016-08-25 13:26:12 Content-Length: 10158080
2016-08-25 13:26:12 Content-Range: bytes 10158080-20316159/251658240
2016-08-25 13:26:15 Status code: 202
....
```

**Comment by rootik** [comment]
Simple file upload to non-existent nested folder:
```
./onedriveb-upload -d -f Backup/test README.md
2016-08-25 13:36:26 Searching for 'Backup' in ''
2016-08-25 13:36:27 Searching for 'test' in '01KB37ZVTBLCBYMBMQMJAKFVVCBYYFLH4Q'
2016-08-25 13:36:28 Creating folder 'test' in '01KB37ZVTBLCBYMBMQMJAKFVVCBYYFLH4Q'
2016-08-25 13:36:29 api_folder_id is now '01KB37ZVS53G3I4AJZUVEJPAKODSMI5TWE'
2016-08-25 13:36:29 Size of README.md is less than or equal to 104857600 bytes, will use simple upload
2016-08-25 13:36:33 Uploading 'README.md' as 'README.md' into 01KB37ZVS53G3I4AJZUVEJPAKODSMI5TWE
Successfully uploaded 'README.md' as 'README.md'

```

**Comment by fkalis** [comment]
Thank you for your contribution. I have just merged your additional script into the master branch.

**Pull request merged**
